[profile.default]
src = "./solidity/src"
out = "./solidity/out"
libs = ["./solidity/lib"]
script = "./solidity/script"
test = "./solidity/test"


remappings = [
  "@openzeppelin/=./solidity/lib/openzeppelin-contracts/"
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# --- Make CREATE2 deterministic across environments/versions ---
# Removes metadata hash / CBOR metadata that otherwise changes initcode hash.
bytecode_hash = "none"
cbor_metadata = false
