name: E2E test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    name: Flow Yield Vaults E2E Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23.x"
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Flow CLI
        run: sh -ci "$(curl -fsSL https://raw.githubusercontent.com/onflow/flow-cli/master/install.sh)"
      - name: Flow CLI Version
        run: flow version
      - name: Update PATH
        run: echo "/root/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: flow deps install --skip-alias --skip-deployments
      - name: Run Emulator
        run: ./local/run_emulator.sh
      - name: Setup Wallets
        run: ./local/setup_wallets.sh
      - name: Run EVM gateway
        run: ./local/run_evm_gateway.sh
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Deploy Punchswap contracts
        run: ./local/punchswap/setup_punchswap.sh
      - name: Setup Punchswap pools
        run: ./local/punchswap/e2e_punchswap.sh
      - name: Setup Emulator
        run: ./local/setup_emulator.sh
      - name: Setup bridged tokens
        run: ./local/setup_bridged_tokens.sh
      - name: Run E2E test
        run: ./local/e2e_test.sh
